# Generated by Django 4.1.4 on 2022-12-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company4duration',
            new_name='company3duration',
        ),
    ]
