# Generated by Django 4.1.4 on 2022-12-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_company4duration_employeeexperience_company3duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='jioningdate',
            new_name='joiningdate',
        ),
    ]
